-- Rename messages.twilio_message_sid -> messages.message_key, phase 2 of 2.
--
-- Phase 1 (20260903150000) added message_key, backfilled it, and installed a
-- trigger mirroring the two columns so code deployed before the rename kept
-- working. Every Edge Function has since been redeployed writing message_key,
-- and each was checked to boot. This drops the old column and the scaffolding.
--
-- Guarded: refuse to drop if the two columns ever disagreed, rather than
-- silently discarding a value that only exists under the old name. Dropping a
-- column cannot be undone, so this asserts the copy is complete first.

do $$
declare
  mismatched bigint;
begin
  select count(*) into mismatched
    from public.messages
   where twilio_message_sid is distinct from message_key;

  if mismatched > 0 then
    raise exception
      'refusing to drop twilio_message_sid: % row(s) differ from message_key', mismatched;
  end if;
end
$$;

drop trigger if exists messages_sync_message_key on public.messages;
drop function if exists public.sync_message_key();

alter table public.messages drop column if exists twilio_message_sid;

comment on column public.messages.message_key is
  'Unique per-message key. Inbound: the provider''s message id. Outbound: generated by us (smartsend-<uuid>), because the gateway returns no id; sim-<uuid> for simulator turns and undelivered-<uuid> for a failed send. Used for idempotency against webhook retries and for the "is this still the newest message" debounce check. Deliberately not named after any provider.';
