-- ============================================================================
-- Human-facing request number
-- ----------------------------------------------------------------------------
-- requests.id is a uuid — fine for joins, useless to show a customer. The
-- approved WhatsApp templates (primeos_deliverable_image and the four
-- notification templates) take "מספר הבקשה" as a parameter, so every request
-- now carries a short ascending integer.
--
--   requests.request_number  bigint  -- auto-assigned, 1, 2, 3, …
--                                     -- existing rows are backfilled by
--                                     -- creation order.
--
-- "by default as identity" (not "always") so a manual backfill / import can
-- still set the column explicitly if ever needed.
-- ============================================================================

alter table public.requests
  add column if not exists request_number bigint;

-- Backfill existing rows in creation order before attaching the identity.
with ordered as (
  select id, row_number() over (order by created_at, id) as n
  from public.requests
)
update public.requests r
  set request_number = ordered.n
  from ordered
  where ordered.id = r.id
    and r.request_number is null;

-- Postgres requires NOT NULL before an identity can be attached.
alter table public.requests
  alter column request_number set not null;

alter table public.requests
  alter column request_number add generated by default as identity;

-- Start the identity sequence past the backfilled rows.
select setval(
  pg_get_serial_sequence('public.requests', 'request_number'),
  coalesce((select max(request_number) from public.requests), 0) + 1,
  false
);

create unique index if not exists requests_request_number_idx
  on public.requests (request_number);

comment on column public.requests.request_number is
  'Short ascending customer-facing request id. Shown in WhatsApp templates.';
